apiVersion: v1
kind: Service
metadata:
  name: pepsi-service
  labels:
    app: pepsi-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pepsi-service
  type: NodePort